<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\LabelRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

use Dcw\CategoryFilterAttribute\ViewModel\ExcludeProductAttribute;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var \Dcw\CategoryFilterAttribute\ViewModel\ExcludeProductAttribute $excludeProductAttributeViewModel
 * @var ViewModelRegistry $viewModels
 */
$excludeProductAttributeViewModel = $viewModels->require(ExcludeProductAttribute::class);
$helper = $this->helper('WeltPixel\GA4\Helper\Data');
$currentCategory = $helper->getCurrentCategory();
$excludeProductAttribute = $currentCategory->getData('exclude_product_attribute');

$attributeCode  = $block->getAttributeCode();
$cacheKey       = rand(100000, 1000000);
$filterAccessor = $attributeCode . 'A' . $cacheKey . 'A';
$filter         = $block->getFilter();

$useAlphabeticalIndex = strpos(get_class($filter), 'AttributeFilter') !== false && $filter->isUseAlphabeticalIndex();

$checkedItemsCount = 0;

$letter  = '';
$revenueHelper = $this->helper('Dcw\RevenueRanking\Helper\Data');
$filter_counts = $revenueHelper->getActiveFilterCount();
?>

<div data-mst-nav-filter="<?= $filterAccessor ?>" data-mst-nav-cache-key="<?= $cacheKey ?>" data-mst-attribute="<?= $attributeCode ?>" class="mst-nav__label" x-data="initLabelRenderer()">
    <?= $block->getSearchBoxElement($filterAccessor) ?>
    <div
        data-holder="alphabetical"
        x-data="initAlphabeticalIndex(<?= (int)($useAlphabeticalIndex && $filter->isAlphabeticalIndexAllowedByLimit()) ?>, <?= $filter->getAlphabeticalLimit() ?>)"
        x-init="init()"
    ></div>

    <ol class="items">
        <?php
            $labelRemoved = 0;
            foreach ($block->getFilterItems() as $key => $filterItem) :
            $label = $filterItem->getData('label');
            if (!empty($excludeProductAttribute)) {
                $result =$excludeProductAttributeViewModel->shouldShowAttributeFilter($label, $attributeCode, $excludeProductAttribute);
                if ($result) {
                    $labelRemoved++;
                    continue;
                }
            }

            $numberOfResults = $filterItem->getData('count');

            $isItemChecked = $block->isFilterItemChecked($filterItem, true);

            $imageUrl         = $block->getImageUrl($filterItem);
            $isFullWidthImage = $block->isFullWidthImage($filterItem);

            if ($isItemChecked) {
                $checkedItemsCount++;
            }

            $cssClass = [
                'item',
                'mst-nav__label-item',
                '_mode-' . $block->getFilterItemDisplayMode($attributeCode),
                $isItemChecked ? '_checked' : '',
                $isItemChecked && $block->isHighlightEnabled() ? '_highlight' : '',
                $imageUrl ? '_image' : '',
                $imageUrl && $isFullWidthImage ? '_full-width' : '',
            ];
            ?>

            <?php if (
                $useAlphabeticalIndex
                && $filter->isSortByLabel()
                && $letter !== $block->getFirstLetter($label)
            ):
            $letter = $block->getFirstLetter($label);
            ?>
            <li class="mst-nav__letter mst-nav__label-item" data-letter="<?= $letter ?>" data-element = filter>
                <b><?= $letter ?></b>
            </li>
            <?php endif ?>

            <li data-element="filter"
                data-hidden="false"
                data-search-hidden="false"
                data-letter-hidden="false"
                class="<?= implode(' ', $cssClass) ?>"
                data-value="<?= $filterItem->getValueString() ?>"
                @click="handleClick"
                <?= $useAlphabeticalIndex ? 'data-letter="' . $block->getFirstLetter($label) . '"' : '' ?>
            >
                <?php if ($numberOfResults >= 0): ?>
                    <?php
                    $url = $isItemChecked ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
                    $id  = $block->getItemId($filterItem);
                    $final_url = $escaper->escapeUrl($url);
                    if (!str_contains($final_url, 'product_list_mode=list')) {
                        $final_url .= "&product_list_mode=list";
                    }
					if (str_contains($final_url, 'product_list_dir')) {
						// Replace existing product_list_dir=xxx with product_list_dir=desc
						$final_url = preg_replace('/product_list_dir=[^&]*/', 'product_list_dir=desc', $final_url);
					} else {
						// If not present, append
						$final_url .= (str_contains($final_url, '?') ? '&' : '?') . "product_list_dir=desc";
					}
					if($filter_counts==1 && $isItemChecked){
						$final_url = str_replace('product_list_order=revenue_ranking', 'product_list_order=position', $final_url);
						$final_url = str_replace('product_list_dir=desc', 'product_list_dir=asc', $final_url);
					}else{
						  if (str_contains($final_url, 'product_list_order')) {
							// Replace existing product_list_order=xxx with product_list_order=revenue_ranking
							$final_url = preg_replace('/product_list_order=[^&]*/', 'product_list_order=revenue_ranking', $final_url);
						} else {
							// If not present, append
							$final_url .= (str_contains($final_url, '?') ? '&' : '?') . "product_list_order=revenue_ranking";
						}
					}
					
                    ?>
                    <a href="<?= $final_url ?>"
                       rel="<?= $block->getRelAttributeValue() ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr($label) ?>"
                    >
                        <?php if ($imageUrl): ?>
                            <div class="swatch-option image" style="background: url(<?= $imageUrl ?>) no-repeat center;  background-size: auto 100%;"></div>
                        <?php endif ?>

                        <input id="<?= $id ?>" type="checkbox" <?= $isItemChecked ? 'checked' : '' ?> />

                        <label for="<?= $id ?>">
                            <span class="mst-nav__label-item__label"><?= $label ?></span>
                            <?php if ($block->getCountElement($filterItem)): ?>
                                <span class="count text-primary"><?= $filterItem->getData('count') ?></span>
                            <?php endif; ?>
                        </label>
                    </a>
                <?php else: ?>
                    <span class="mst-nav__label-item__label"><?= $label ?></span>
                    <?php if ($block->getCountElement($filterItem)): ?>
                        <span class="count text-primary"><?= $filterItem->getData('count') ?></span>
                    <?php endif; ?>
                <?php endif ?>
            </li>
        <?php endforeach ?>

        <?= $block->getSizeLimiterElement($filterAccessor) ?>
    </ol>

    <div class="hidden mst-clear-options-link" data-checked-count="<?= $checkedItemsCount ?>">
        <div class="mst-nav__checked-counter__wrapper flex items-center mx-2">
            <div class="mst-nav__checked-counter rounded px-2 bg-gray-200 mr-1"><?= $checkedItemsCount ?></div>
            <a class="hover:underline text-2xl opacity-50" href="<?= $block->getAttributeClearUrl($attributeCode) ?>" data-element="filter">&#10005;</a>
        </div>
    </div>
    <?php if ($labelRemoved == $filter->getItemsCount()) : ?>
        <script type="text/javascript">
            document.getElementById("filter-id-<?= $attributeCode ?>").style.display = "none";
        </script>
     <?php endif; ?>
</div>
