<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php 
$_order = $block->getOrder();
if ($_order) : ?>
    <?php
        $payment = $_order->getPayment();
        $paymentMethod = $payment->getMethodInstance();
        $paymentMethodTitle = $paymentMethod->getTitle();
        $dcwCheckoutBlock = $block->getLayout()->createBlock(\Dcw\Checkout\Block\Index::class);
        $shippingAddress = $_order->getShippingAddress();
    ?>
    <?php $_items = $_order->getAllItems(); ?>
    <h3 style="font-weight: 700;font-size: 16px;line-height: 24px;margin:0 0 5px 0 !important;color: #000000;padding-left: 30px;">Items Ordered</h3>
    <table class="email-items" border="0" width="100%" cellpadding="0" cellspacing="0" align="center">
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tr>
            <td width="30">&nbsp;</td>
            <td style="width: 50%;box-sizing: border-box;">
                <h3>Shipping Address</h3>
                <?php if ($shippingAddress) {?>
                    <?= $dcwCheckoutBlock->orderAddressRenderer()->format($shippingAddress, 'html'); ?>
                <?php }?>
            </td>
            <td style="vertical-align: top;">
                <h3>Paid with <?= $paymentMethodTitle ?></h3>
                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                    <?= $block->getChildHtml('order_totals') ?>
                </table>
            </td>
            <td width="30">&nbsp;</td>
        </tr>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
