<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\LocaleFormatter;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer;

/** @var DefaultRenderer $block */
/** @var Escaper $escaper */
/** @var LocaleFormatter $localeFormatter */

use Hyva\Theme\Model\ViewModelRegistry;
use Dcw\ShoppingCart\ViewModel\Data as ShoppingCartData;
/** @var ViewModelRegistry $viewModels */
/** @var ShoppingCartData $shoppingCartData */

$shoppingCartData = $viewModels->require(ShoppingCartData::class);

$item = $block->getItem();
$cols = $block->getData('is_context_shipment') ? 3 : ($block->getData('is_context_creditmemo') ? 7 : 5);
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

// Check if it's from an order
$promiseDate = "";
$estimateShipping = 'N/A';
if ($item->getOrder()) {
    $pdpLineItem = $item->getPdpLineItem();
    $pdplineitemObject = json_decode($pdpLineItem ?? '');
    $estimateShipping = "N/A";
    $promiseDate = "";

    if ($pdplineitemObject!==null) {
        if (isset($pdplineitemObject->shipping_estimate)) {
            $estimateShipping = $pdplineitemObject->shipping_estimate;
        }

        if (isset($pdplineitemObject->promise_date)) {
            $promiseDate = $pdplineitemObject->promise_date;
        }
    }
}

$isNotPastDate=0;
if($promiseDate){
	$current_date = $shoppingCartData->getCurrentDate();
	if (strpos($promiseDate, '-') !== false) {
        // Date range
        list($start, $end) = explode('-', $promiseDate);
		$endDate = date('Y-m-d', strtotime(trim($end)));

        if ($current_date <= $endDate) {
            $isNotPastDate=1;
        } else {
            $isNotPastDate=0;
        }

    } else {
        // Single date
        $pdate = date('Y-m-d', strtotime($promiseDate));
		if ($pdate >= $current_date) {
			$isNotPastDate=1;
		}
    }
}
?>
<?php 
    $pre_order_message = '';
	if ($estimateShipping === '' || $estimateShipping === 'N/A') {
		$productId = $item->getProductId();
		$options   = $item->getProductOptions();

		// Default (parent)
		$childProductId = $item->getProductId();

		// Check if child product ID is stored in options
		if ($item->getProduct() && $item->getProduct()->getTypeId()=='configurable'){
			if (isset($options['info_buyRequest']['selected_option_child_id'])) {
				$childProductId = $options['info_buyRequest']['selected_option_child_id'];
			}elseif (array_key_exists('simple_sku',$options)){
				$simple_sku = $options['simple_sku'];
				$childProductId = $shoppingCartData->getProductBySku($simple_sku);
			}
		}

		// Check if preorder applies
		$checkForQtyBackorderdata = $shoppingCartData->checkForQtyBackorderData(
			$childProductId,
			$item->getQtyOrdered()
		);

		if ($checkForQtyBackorderdata) {
			$pre_order_message = $checkForQtyBackorderdata;
			if ($promiseDate && $isNotPastDate) {
				$pre_order_message .= " [Estimated ship date: " . $promiseDate . "]";
			}
		}
	}
?>


    <?php if ($item->getOrder()) { ?>
        <div class="lg:grid grid-cols-7 py-2">
    <?php } else { ?>
        <div class="lg:grid grid-cols-6 py-2">
    <?php } ?>
    <div class="p-2 product_name flex justify-between w-full">
        <div class="product_name_in">
            <span class="font-semibold"><?= $escaper->escapeHtml($item->getName()) ?></span>
            <div class="item-options mt-2">
                <!-- <div class="text-sm flex">
                    <span><?= $escaper->escapeHtml(__('Sku')) ?>:</span>
                    <span class="text-sm ml-1"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></span>
                </div> -->
                <?php if ($options = $block->getItemOptions()): ?>
                    <?php foreach ($options as $option): ?>
                        <?php
                        $skipLabels = [
                                'Colors',
                                'Color',
                                'Select An Option',
                                'Configurable Product Id',
                                'Configurable Product Url',
                                'Configurable Product Image',
                                'Main Configurable Product Image',
                                'Product Name',
                                'Configurable Product SKU',
                                'Configurable Product Category',
                                'Configurable Product Name',
								'Color Display Name'
                            ];
                            
                            if (in_array($option['label'], $skipLabels)) {
                                continue;
                            }
                        ?>
                        
                        <div class="text-sm flex mt-1">
                            <span><?= $escaper->escapeHtml($option['label']) ?>:</span>
                            <?php if (!$block->getPrintStatus()): ?>
                                <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                <span class="ml-1">
                                    <?= $escaper->escapeHtml($formatedOptionValue['value'], ['a']) ?>
                            </span>
                            <?php else: ?>
                                <span class="ml-1">
                                    <?= $escaper->escapeHtml(
                                        (isset($option['print_value']) ? $option['print_value'] : $option['value'])
                                    ) ?>
                                </span>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php /* downloadable */ ?>
                <?php if ($links = $block->getLinks()): ?>
                    <div class="item options my-2">
                        <p><?= $escaper->escapeHtml($block->getLinksTitle()) ?></p>
                        <?php foreach ($links->getPurchasedItems() as $link): ?>
                            <p class="ml-1"><?= $escaper->escapeHtml($link->getLinkTitle()) ?></p>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addtInfoBlock): ?>
                    <?= $addtInfoBlock->setItem($item)->toHtml() ?>
                <?php endif; ?>
                <?= $escaper->escapeHtml($item->getDescription()) ?>
            </div>
        </div>
    </div>
	<div class="p-2 sku flex justify-between hidden text-size14 font-medium text-black"><?= $escaper->escapeHtml($item->getSku()) ?></div>
    <div class="p-2 qty flex justify-between lg:block text-size14 font-medium text-black">
        <div class="text-right lg:text-left">
            <?php if ($block->getData('is_context_invoice') || $block->getData('is_context_creditmemo')): ?>
                <span class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQty()) ?></span>
            <?php endif; ?>
            <?php if ($block->getData('is_context_shipment')): ?>
                <span class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQty()) ?></span>
            <?php endif; ?>
            <?php if ($block->getData('is_context_order')): ?>
                <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                    <p>
                        <!--<span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?>:</span>-->
                        <span class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyOrdered()) ?></span>
                    </p>
                <?php endif; ?>
                <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                    <p>
                        <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?>:</span>
                        <span class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyShipped()) ?></span>
                    </p>
                <?php endif; ?>
                <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                    <p>
                        <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?>:</span>
                        <span class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyCanceled()) ?></span>
                    </p>
                <?php endif; ?>
                <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                    <p>
                        <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?>:</span>
                        <span class="content"><?= /** @noEscape */ $localeFormatter->formatNumber($block->getItem()->getQtyRefunded()) ?></span>
                    </p>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
	<div class="p-2 size flex justify-between lg:block text-size14 font-medium text-black">
	<?php if ($options = $block->getItemOptions()): ?>
		<?php foreach ($options as $option): ?>
			<?php if($option['label'] =="Select An Option"){
				$formatedOptionValue = $block->getFormatedOptionValue($option)?>
				<?= $escaper->escapeHtml($formatedOptionValue['value'], ['a']) ?>
			<?php } ?>
		<?php endforeach; ?>
    <?php endif; ?>
	</div>
	<div class="p-2 color flex justify-between lg:block text-size14 font-medium text-black">
	<?php if ($options = $block->getItemOptions()): ?>
		<?php foreach ($options as $option): ?>
			<?php if($option['label'] =="Color" || $option['label'] == "Colors"){
				$formatedOptionValue = $block->getFormatedOptionValue($option)?>
				<?= $escaper->escapeHtml($formatedOptionValue['value'], ['a']) ?>
			<?php } ?>
		<?php endforeach; ?>
    <?php endif; ?>
	</div>
    <?php if ($item->getOrder()) { ?>
        <div class="p-2 estimate_shipping flex justify-between lg:block text-size14 font-medium text-black">
            <p class="shipping-estimate"><?php echo $estimateShipping;?></p>
			<?php if ($estimateShipping === '' || $estimateShipping === 'N/A') { ?>
				<?php if ($pre_order_message) { ?>
					<p class="promise-date"><?php echo $pre_order_message;?></p>
				<?php } ?>
			<?php } ?>
        </div>
    <?php } ?>
	<div class="p-2 discount_amount flex justify-between lg:block text-size14 font-medium text-black">
	<?php echo $priceHelper->currency($item->getDiscountAmount(), true, false).' ('.number_format((int)$item->getDiscountPercent(),2).' %)';?>
	</div>
    <?php if (!$block->getData('is_context_shipment')): ?>
        <div class="p-2 flex justify-between lg:block text-right text-size14 font-medium text-black">
            <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Subtotal')) ?></p>
            <?= $block->getItemRowTotalHtml() ?>
        </div>
    <?php endif; ?>
	</div>
    <?php if (!$block->getData('is_context_shipment')): ?>
        <!--<div class="p-2 flex justify-between lg:block">
            <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Price')) ?></p>
            <?= $block->getItemPriceHtml() ?>
        </div>-->
    <?php endif; ?>
    
    
    <?php if ($block->getData('is_context_creditmemo')): ?>
        <div class="p-2 text-right flex justify-between lg:block">
            <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Discount Amount')) ?></p>
            <?= /* @noEscape */ $block->getOrder()->formatPrice($item->getDiscountAmount()) ?>
        </div>
        <div class="p-2 text-right flex justify-between lg:block">
            <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Row Total')) ?></p>
            <?= $block->getItemRowTotalAfterDiscountHtml() ?>
        </div>
    <?php endif; ?>
    