<?php
/** @var \Mirasvit\GdprConsent\Block\ConsentCheckbox $block */
?>

<div class="field choice consent">
    <input
            type="checkbox"
            name="is_consented"
            title="Sign Up for Newsletter"
            value="1"
            id="is_consented"
            class="checkbox"
            data-validate="{required:true}">
    <label for="is_consented" class="label"><span>I agree to the <a href="/privacy-policy" target="_blank">Privacy Policy</a></span></label>
</div>
