<?php
$headerMobileTop = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_mobile_top')->toHtml();

if($headerMobileTop != ''): ?>
    <div class="customer-satisfaction-container">
        <?php echo $headerMobileTop; ?>
    </div>
<?php endif; ?>
<div x-data="notificationAjaxCall()" x-init="initNotificationFunc()" class="header_left_notification_main p-3 bg-[#CAD5DB]">
    <div class="header_left_notification text-size14 font-normal leading-[20px]" x-html="left_notification_html"></div> 
    <div class="header_left_notification_track leading-[20px]"><a href="/sales/guest/form" class="block leading-[20px] text-[14px] font-normal text-[#15324C]">Track Order</a></div>
</div>

<script>
function notificationAjaxCall() {
    return {
        availability_notification: '',
        left_notification_html: '',
        right_notification_html: '',
        initNotificationFunc: function () {
            fetch(BASE_URL+'notifications/index/show', {
                method: "GET",
                headers: { 'Content-Type': 'application/json' },
            })
            .then(response => {
                if (! response.ok) console.warn('GET request failed');
                return response.json();
            })
            .then(data => {
                if (data) {
                  //this.availability_notification = data.availability_notification;
                  this.left_notification_html = data.left_notification_html;
                  //this.right_notification_html = data.right_notification_html;
                }
            });
        }
    }
}
</script>