<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */
declare(strict_types=1);

use Magento\DataServices\Block\Context;

/**
 * @var Context $block
 */

?>

<script>
    window.addEventListener('load', function () {
        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });

        <?php //cartId is set inside Hyva_MagentoDataServices::set-cart-context.phtml ?>
    });
    window.addEventListener('shoppingCartContextSet', function () {
        magentoStorefrontEvents.publish.shoppingCartView();
    });
</script>

