<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */
declare(strict_types=1);

use Magento\DataServices\Block\Context;
use Magento\DataServices\ViewModel\WishListProvider;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var Context $block
 * @var WishListProvider $viewModel
 * @var ViewModelRegistry $viewModels
 */

$viewModel = $viewModels->require(WishListProvider::class);
$userAction = $viewModel->getUserAction();
$pageAction = $userAction ?: $block->getData('step_name');

?>

<script>
    window.addEventListener('load', function () {
        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });
        magentoStorefrontEvents.context.setShoppingCart({
            id: <?= /* @noEscape */ $block->getCartId(); ?>
        });
    });
</script>
