<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
declare(strict_types=1);

use Dcw\Custom\ViewModel\Data;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

$productId = (int)$block->getProductId();

$attributeId = (int)$block->getAttributeId();

if (!$productId || !$attributeId) {
    return '';
}

/** @var Data $blockObj */
$blockObj = $viewModels->require(Data::class);

$product =  $blockObj->getLoadProduct($productId);

$attr = $blockObj->getAttributeById($attributeId);

$attributeCode = $attr->getAttributeCode();

$getCustomSwatchData = $blockObj->getSwatchProducts($product);
$getCustomSwatchDataDecode = json_decode($getCustomSwatchData, true);
$swatchImageUrl = "";

if (isset($getCustomSwatchData) && is_array($getCustomSwatchDataDecode)) {
    $swatchImageUrl = json_encode($getCustomSwatchDataDecode['swatchUrl']);
}
?>
<div>
    <template x-if="optionIsEnabled(<?= $attributeId ?>, item.id) && optionIsActive(<?= $attributeId ?>, item.id)">
        <label
            :for="'attribute-option-<?= $productId ?>-'+item.id"
            class="swatch-option relative border-2 shadow-sm cursor-pointer select-none bg-container-lighter product-option-value-label"
            :class="{
                'border-container-lighter ring ring-primary/50':
                    (selectedValues[<?= $attributeId ?>] === item.id),
                'border-container-darker':
                    (selectedValues[<?= $attributeId ?>] !== item.id),
                'w-6 h-6' : !isTextSwatch(<?= $attributeId ?>, item.id),
                'border-container-lighter ring ring-primary/75' : focusedLabel === item.id
            }"
            :style="getSwatchBackgroundStyle('<?= $attributeId ?>',item.id)"
            <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
                @mouseenter.self="activeTooltipItem = {
                    attribute: '<?= $attributeId ?>',
                    item: item.id
                }; tooltipPositionElement = $event.target;"
                @mouseleave.self="activeTooltipItem = false"
            <?php endif; ?>
        >
            <input
                :id="'attribute-option-<?= $productId ?>-'+item.id"
                :value="item.id"
                name="super_attribute[<?= $attributeId ?>]"
                type="radio"
                class="inline-block absolute p-0 border-0 focus:border-0 focus:ring-0 product-option-value-input"
                style="z-index:-1"
                x-on:focus="focusLabel(item.id)"
                x-on:blur="blurLabel()"
                x-on:change="changeOption(<?= $attributeId ?>, $event.target.value)"
                x-model="selectedValues[<?= $attributeId ?>]"
                :required="getAllowedAttributeOptions(<?= $attributeId ?>).filter(
                                                                    attributeOption => selectedValues[attributeOption]
                                                                ).length === 0"
            >
            <div class="whitespace-nowrap"
                 :class="{ 'sr-only' : !isTextSwatch(<?= $attributeId ?>, item.id) }"
            >
            <?php if ($attributeCode == 'incstores_pim_color_axis') { ?>
                <span x-html="getSwatchTextUrl(<?= $attributeId ?>, item.id, JSON.parse('<?php echo htmlspecialchars($swatchImageUrl, ENT_QUOTES, 'UTF-8'); ?>'))"  :id="'child-color-<?= $attributeId ?>-'+item.id"></span>
            <?php } else { ?>
                <span x-html="getSwatchText(<?= $attributeId ?>, item.id)"></span>
            <?php } ?>
            </div>
        </label>
    </template>

    <template x-if="optionIsEnabled(<?= $attributeId ?>, item.id) && !optionIsActive(<?= $attributeId ?>, item.id)">
        <div
            class="relative border-2 shadow-sm opacity-50 cursor-pointer select-none border-container-darker swatch-option bg-container-lighter hidden"
            :class="{
                                                        'w-6 h-6' : !isTextSwatch(<?= $attributeId ?>, item.id),
                                                    }"
            :style="getSwatchBackgroundStyle('<?= $attributeId ?>',item.id)"
        >
            <div x-html="getSwatchText(<?= $attributeId ?>, item.id)"
                 class="whitespace-nowrap"
                 :class="{ 'sr-only' : !isTextSwatch(<?= $attributeId ?>, item.id) }"
            ></div>
            <svg class="absolute inset-0 w-full h-full text-gray-500 bg-white/25">
                <line x1="0" y1="100%" x2="100%" y2="0" class="stroke-current stroke-1"></line>
            </svg>
        </div>
    </template>
</div>
