<script>
    window.addEventListener("scroll", function() {
        var header = document.querySelector('header.page-header');
        var body = document.querySelector("body");
        const header_top = document.querySelector('.header_top');
        const notification4 = document.querySelector('.notification4');
        var top_1 = document.querySelector("header.page-header > .panel.wrapper");
        var content = document.getElementById("textContent");


        if(header_top && notification4){
            if ((header_top.textContent.length > 10) && (notification4.textContent.length > 10)) {
                if (window.pageYOffset > 76) {
                    //document.querySelector("#header").style.cssText = "position:fixed;left:0;top:0;width:100%;transition: all ease-in-out 0.5s";
                    //document.querySelector(".page-wrapper").style.cssText = "padding-top:112px";
                    document.querySelector('body').classList.add('sticki');
                } else {
                    //document.querySelector("#header").style.cssText = "position:static;transition: all ease-in-out 0.5s";
                    //document.querySelector(".page-wrapper").style.cssText = "padding-top:0px";
                    document.querySelector('body').classList.remove('sticki');
                }
            }
        }

        if(header_top && notification4){
            if ((header_top.textContent.length > 10) && (notification4.textContent.length < 10)) {
                if (window.pageYOffset > 36) {
                    //document.querySelector("#header").style.cssText = "position:fixed;left:0;top:0;width:100%;transition: all ease-in-out 0.5s";
                    //document.querySelector(".page-wrapper").style.cssText = "padding-top:112px";
                    document.querySelector('body').classList.add('sticki');
                } else {
                    //document.querySelector("#header").style.cssText = "position:static;transition: all ease-in-out 0.5s";
                    //document.querySelector(".page-wrapper").style.cssText = "padding-top:0px";
                    document.querySelector('body').classList.remove('sticki');
                }
            }
        }

        if(header_top && !notification4){
            if (header_top.textContent.length > 10) {
                if (window.pageYOffset > 36) {
                    //document.querySelector("#header").style.cssText = "position:fixed;left:0;top:0;width:100%;transition: all ease-in-out 0.5s";
                    //document.querySelector(".page-wrapper").style.cssText = "padding-top:112px";
                    document.querySelector('body').classList.add('sticki');
                } else {
                    //document.querySelector("#header").style.cssText = "position:static;transition: all ease-in-out 0.5s";
                    //document.querySelector(".page-wrapper").style.cssText = "padding-top:0px";
                    document.querySelector('body').classList.remove('sticki');
                }
            }
        }
    });

    window.addEventListener("DOMContentLoaded", function() {
        window.addEventListener("scroll", function() {
            // scroll for plp content sticky
            anchor_scroll();
        });
        function anchor_scroll() {
            var anchor_scroll = document.querySelector('.anchor-scroll');
            if (!anchor_scroll) {
                return; // Exit if the element is not found
            }
            let sticky = anchor_scroll.offsetTop;

            if (window.pageYOffset > sticky) {
                anchor_scroll.classList.add("scroll-fixed");
            } else {
                anchor_scroll.classList.remove("scroll-fixed");
            }
        }

        document.querySelectorAll('.anchor-scroll a[href^="."], .at-glance-content a[href^="."]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();

                const targetClass = this.getAttribute('href').substring(1);
                const targetElement = document.querySelector(`.${targetClass}`);
                let anchor_scroll = document.querySelector('.anchor-scroll > div');
                var header_off = document.querySelector('#header').offsetHeight;
                if (anchor_scroll) {
                    var header_off = document.querySelector('#header').offsetHeight + anchor_scroll.offsetHeight;
                } else {
                    var header_off = document.querySelector('#header').offsetHeight;
                }

                if (targetElement) {
                    const offset = header_off;
                    const bodyRect = document.body.getBoundingClientRect().top;
                    const elementRect = targetElement.getBoundingClientRect().top;
                    const elementPosition = elementRect - bodyRect;
                    const offsetPosition = elementPosition - offset;

                    window.scrollTo({
                        top: offsetPosition,
                        behavior: 'smooth'
                    });
                }
            });
        });
    });
</script>
