<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="w-full">
    <form class="form subscribe" 
          action="<?= $escaper->escapeUrl($block->getUrl('newsletter/subscriber/new/')) ?>"
          method="post"
          x-data="initCustomNewsletterForm()"
          @submit.prevent="submitForm()"
          id="newsletter-validate-detail-alt"><!-- unique ID -->
        <div class="flex flex-wrap justify-center gap-2 md:justify-start subscribe-in">
            <label for="newsletter-subscribe-alt" class="sr-only">
                <?= $escaper->escapeHtml(__('Email Address')) ?>
            </label>
            <input name="email"
                   type="email"
                   required
                   id="newsletter-subscribe-alt" 
                   class="form-input inline-flex w-full"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('you@example.com')) ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button class="btn btn-secondary"> <!-- different button style -->
                <?= $escaper->escapeHtml(__('Submit')) ?>
            </button>
        </div>
        <div>
            <template x-if="displayErrorMessage">
                <p class="flex items-center text-red">
                    <span class="inline-block w-8 h-8 mr-3">
                        <?= $heroicons->exclamationCircleHtml(); ?>
                    </span>
                    <template x-for="errorMessage in errorMessages">
                        <span x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>
    </form>
    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
    <script>
        function initCustomNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Use the unique form ID here
                    const $form = document.querySelector('#newsletter-validate-detail-alt');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    const emailField = $form.querySelector('#newsletter-subscribe-alt');
                    const emailValue = emailField.value.trim();
                    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                    if (!emailRegex.test(emailValue)) {
                        this.setErrorMessages("<?= $escaper->escapeJs(__('Please enter a valid email address.')) ?>");
                        return;
                    }

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>

<div class="pr-4 lg:w-1/4 md:w-1/2">

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_right_link')->toHtml();?>
</div>    